language: php

php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  allow_failures:
    - php: 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer
    - vendor

git:
  depth: 1

install:
  - 'cp -f config/parameters.yml.dist config/parameters.yml'
  - composer install -n --no-progress --prefer-dist

script:
  - bin/phpunit
  - bin/phpstan analyse
