language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - 'cp -f app/config/parameters.yml.dist app/config/parameters.yml'
  - composer install -n --dev --no-progress

script:
  - bin/phpunit
