imports:
  - { resource: parameters.yml }
  - { resource: security.yml }

framework:
  secret: "%secret%"
  session: ~
  templating:
    engines: ['twig']
  assets: ~
  profiler:
    collect: false
  lock:
    resources:
      satis: "flock"

twig:
  form_themes: ['bootstrap_3_layout.html.twig']
