imports:
  - { resource: defaults.yml }
  - { resource: parameters.yml }
  - { resource: security.yml }

parameters:
  container.autowiring.strict_mode: true

framework:
  secret: "%secret%"
  session: ~
  templating:
    engines: ['twig']
  assets: ~
  profiler:
    collect: false
  lock:
    resources:
      satis: "flock"
      build: "flock"

twig:
  form_themes: ['bootstrap_3_layout.html.twig']

monolog:
  handlers:
    errors:
      type: fingers_crossed
      action_level: error
      handler: file_log
    file_log:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      max_files: 30
